# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180306_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blog',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
