# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_member_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Member')),
            ],
        ),
    ]
