# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='high_school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
