# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_education_high_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='member',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
