# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='cgpa',
            new_name='percentage',
        ),
    ]
