# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='members_photo/'),
        ),
    ]
