# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180308_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='snap',
            field=models.ImageField(blank=True, upload_to='project_photo/'),
        ),
    ]
