# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='snap',
            new_name='photo',
        ),
    ]
