# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180308_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(to='home.Team'),
        ),
    ]
