# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_project_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
